development:
  adapter: postgresql
  encoding: unicode
  database: travelinsurance_development
  pool: 5
  username: travelinsurance
  password: travelinsurance

test:
  adapter: postgresql
  encoding: unicode
  database: travelinsurance_test
  pool: 5
  username: travelinsurance
  password: travelinsurance
